#!/usr/bin/env bash

INPUT_FILE="${1:-input.txt}"
if [[ $INPUT_FILE =~ input.txt$ ]]; then
  n_conns=1000
else
  n_conns=10
fi

distance() {
  local x1=$1
  local y1=$2
  local z1=$3
  local x2=$4
  local y2=$5
  local z2=$6

  echo $(( (x2 - x1)**2 + (y2 - y1)**2 + (z2 - z1)**2 ))
}

read -d '\n' -r -a boxes < "$INPUT_FILE"

declare connections=()
if [[ $INPUT_FILE =~ input.txt$ && -f "__cache__/distances.txt" ]]; then
  echo "loading connections from cache..."
  mapfile -t connections < "__cache__/distances.txt"
  echo "  loaded ${#connections[@]} connections from cache"
else
  echo "no connections cache found, computing distances..."
  for ((i=0; i<${#boxes[@]}; i++)); do
    if ((i == 0 || (i+1) % 10 == 0)); then
      echo "  processing box $((i+1))/${#boxes[@]}"
    fi
    for ((j=i+1; j<${#boxes[@]}; j++)); do
      IFS=',' read -r -a box1 <<< "${boxes[i]}"
      IFS=',' read -r -a box2 <<< "${boxes[j]}"
      key="${i},${j}"
      d=$(distance "${box1[@]}" "${box2[@]}")
      connections+=("$d $key")
      [[ $INPUT_FILE =~ input.txt$ ]] && echo "$d $key" >> "__cache__/distances.txt"
    done
  done
fi

mapfile -t connections < <(printf '%s\n' "${connections[@]}" | sort -n)

echo -e "\nbuilding circuits from the closest $n_conns connections..."
circuits=()
iter=1
for conn in "${connections[@]:0:$n_conns}"; do
  read -r _ key <<< "$conn"
  IFS=',' read -r box1 box2 <<< "$key"
  added=false
  for ((i=0; i<${#circuits[@]}; i++)); do
    if [[ ${circuits[i]} =~ (^|,)$box1(,|$) ]]; then
      if [[ ${circuits[i]} =~ (^|,)$box2(,|$) ]]; then
        added=true
        break
      else
        for ((j=0; j<${#circuits[@]}; j++)); do
          if ((i == j)); then
            continue
          fi
          if [[ ${circuits[j]} =~ (^|,)$box2(,|$) ]]; then
            circuits[i]="${circuits[i]},${circuits[j]}"
            unset 'circuits[j]'
            circuits=("${circuits[@]}")  # reindex array
            added=true
            break 2
          fi
        done
      fi
      circuits[i]="${circuits[i]},${box2}"
      added=true
      break
    elif [[ ${circuits[i]} =~ (^|,)$box2(,|$) ]]; then
      for ((j=0; j<${#circuits[@]}; j++)); do
        if ((i == j)); then
          continue
        fi
        if [[ ${circuits[j]} =~ (^|,)$box1(,|$) ]]; then
          circuits[i]="${circuits[i]},${circuits[j]}"
          unset 'circuits[j]'
          circuits=("${circuits[@]}")  # reindex array
          added=true
          break 2
        fi
      done
      circuits[i]="${circuits[i]},${box1}"
      added=true
      break
    fi
  done
  if ! $added; then
    circuits+=("${box1},${box2}")
  fi
  if ((iter == 1 || iter % 10 == 0)); then
    echo "  processed $iter/$n_conns connections"
  fi
  ((iter++))
done

echo -e "\nbuilt ${#circuits[@]} circuits from $n_conns connections"
circuit_lengths=()
for circuit in "${circuits[@]}"; do
  IFS=',' read -r -a box_indices <<< "$circuit"
  circuit_lengths+=("${#box_indices[@]}")
done

mapfile -t circuit_lengths < <(printf '%s\n' "${circuit_lengths[@]}" | sort -rn)
longest_lengths=("${circuit_lengths[@]:0:3}")

echo "  the three longest circuits have lengths: ${longest_lengths[*]}"

result=1
for i in "${circuit_lengths[@]:0:3}"; do
  result=$((result * i))
done

echo -e "\nResult: $result"
